server:
  port: ${PORT:8080}
authorization:
  token: ${TOKEN:security_token}
spring:
  cloud:
    gateway:
      routes:
      - id: image
        uri: http://localhost:8082
        predicates:
        - Path=/api/image/**
        filters:
          - RewritePath=/api/image(?<segment>.*), /$\{segment}
      - id: message
        uri: http://localhost:8083
        predicates:
        - Path=/api/message/**
        filters:
          - RewritePath=/api/message(?<segment>.*), /$\{segment}
      - id: library
        uri: http://localhost:8085
        predicates:
        - Path=/api/library/**
        filters:
          - RewritePath=/api/library(?<segment>.*), /$\{segment}
      - id: stash
        uri: http://localhost:8086
        predicates:
        - Path=/api/stash/**
        filters:
          - RewritePath=/api/stash(?<segment>.*), /$\{segment}
      - id: profile
        uri: http://localhost:8087
        predicates:
        - Path=/api/profile/**
        filters:
          - RewritePath=/api/profile(?<segment>.*), /$\{segment}
      - id: user
        uri: http://localhost:8088
        predicates:
        - Path=/api/user/**
        filters:
          - RewritePath=/api/user(?<segment>.*), /$\{segment}
