logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG

server:
  port: ${PORT:8080}
authorization:
  token: ${TOKEN:security_token}
app:
  image:
    url: http://localhost:8082
  message:
    url: http://localhost:8083
  library:
    url: http://localhost:8085
  stash:
    url: http://localhost:8086
  profile:
    url: http://localhost:8087
  user:
    url: http://localhost:8088
spring:
  cloud:
    gateway:
      routes:
        - id: image
          uri: ${app.image.url}
          predicates:
            - Path=/api/image/**
          filters:
            - StripPrefix=2
        - id: message
          uri: ${app.message.url}
          predicates:
            - Path=/api/message/**
          filters:
            - StripPrefix=2
        - id: library
          uri: ${app.library.url}
          predicates:
            - Path=/api/library/**
          filters:
            - StripPrefix=2
        - id: stash
          uri: ${app.stash.url}
          predicates:
            - Path=/api/stash/**
          filters:
            - StripPrefix=2
        - id: profile
          uri: ${app.profile.url}
          predicates:
            - Path=/api/profile/**
          filters:
            - StripPrefix=2
        - id: user
          uri: ${app.user.url}
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=2
---
spring:
  profiles: stage
app:
  image:
    url: https://tempvs-image-stage.herokuapp.com
  message:
    url: https://tempvs-message-stage.herokuapp.com
  library:
    url: https://tempvs-library-stage.herokuapp.com:443
  stash:
    url: https://tempvs-stash-stage.herokuapp.com
  profile:
    url: https://tempvs-profile-stage.herokuapp.com
  user:
    url: https://tempvs-user-stage.herokuapp.com
