logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG

server:
  port: ${PORT:8080}
authorization:
  token: ${TOKEN:security_token}
app:
  image:
    name: image
    url: http://localhost:8082
  message:
    name: message
    url: http://localhost:8083
  library:
    name: library
    url: http://localhost:8085
  stash:
    name: stash
    url: http://localhost:8086
  profile:
    name: profile
    url: http://localhost:8087
  user:
    name: user
    url: http://localhost:8088
spring:
  cloud:
    gateway:
      routes:
      - id: ${app.image.name}
        uri: ${app.image.url}
        predicates:
        - Path=/api/${app.image.name}/**
        filters:
          - RewritePath=/api/${app.image.name}(?<segment>.*), /$\{segment}
      - id: ${app.message.name}
        uri: ${app.message.url}
        predicates:
        - Path=/api/${app.message.name}/**
        filters:
          - RewritePath=/api/${app.message.name}(?<segment>.*), /$\{segment}
      - id: ${app.library.name}
        uri: ${app.library.url}
        predicates:
        - Path=/api/${app.library.name}/**
        filters:
          - RewritePath=/api/${app.library.name}(?<segment>.*), /$\{segment}
      - id: ${app.stash.name}
        uri: ${app.stash.url}
        predicates:
        - Path=/api/${app.stash.name}/**
        filters:
          - RewritePath=/api/${app.stash.name}(?<segment>.*), /$\{segment}
      - id: ${app.profile.name}
        uri: ${app.profile.url}
        predicates:
        - Path=/api/${app.profile.name}/**
        filters:
          - RewritePath=/api/${app.profile.name}(?<segment>.*), /$\{segment}
      - id: ${app.user.name}
        uri: ${app.user.url}
        predicates:
        - Path=/api/${app.user.name}/**
        filters:
          - RewritePath=/api/${app.user.name}(?<segment>.*), /$\{segment}
---
spring:
  profiles: stage
app:
  image:
    url: https://tempvs-image-stage.herokuapp.com
  message:
    url: https://tempvs-message-stage.herokuapp.com
  library:
    url: https://tempvs-library-stage.herokuapp.com
  stash:
    url: https://tempvs-stash-stage.herokuapp.com
  profile:
    url: https://tempvs-profile-stage.herokuapp.com
  user:
    url: https://tempvs-user-stage.herokuapp.com
  cloud:
    gateway:
      routes:
        - id: ${app.image.name}
          uri: ${app.image.url}
          predicates:
            - Path=/api/${app.image.name}/**
          filters:
            - RewritePath=/api/${app.image.name}(?<segment>.*), /$\{segment}
        - id: ${app.message.name}
          uri: ${app.message.url}
          predicates:
            - Path=/api/${app.message.name}/**
          filters:
            - RewritePath=/api/${app.message.name}(?<segment>.*), /$\{segment}
        - id: ${app.library.name}
          uri: ${app.library.url}
          predicates:
            - Path=/api/${app.library.name}/**
          filters:
            - RewritePath=/${app.library.name}(?<segment>.*), /$\{segment}
        - id: ${app.stash.name}
          uri: ${app.stash.url}
          predicates:
            - Path=/api/${app.stash.name}/**
          filters:
            - RewritePath=/api/${app.stash.name}(?<segment>.*), /$\{segment}
        - id: ${app.profile.name}
          uri: ${app.profile.url}
          predicates:
            - Path=/api/${app.profile.name}/**
          filters:
            - RewritePath=/api/${app.profile.name}(?<segment>.*), /$\{segment}
        - id: ${app.user.name}
          uri: ${app.user.url}
          predicates:
            - Path=/api/${app.user.name}/**
          filters:
            - RewritePath=/api/${app.user.name}(?<segment>.*), /$\{segment}
