server:
  port: ${PORT:8080}
authorization:
  token: ${TOKEN:security_token}
spring:
  cloud:
    gateway:
      routes:
      - id: image
        uri: http://localhost:8082
        predicates:
        - Path=/image/**
      - id: message
        uri: http://localhost:8083
        predicates:
        - Path=/message/**
      - id: library
        uri: http://localhost:8085
        predicates:
        - Path=/library/**
      - id: stash
        uri: http://localhost:8086
        predicates:
        - Path=/stash/**
      - id: profile
        uri: http://localhost:8087
        predicates:
        - Path=/profile/**
      - id: user
        uri: http://localhost:8088
        predicates:
        - Path=/user/**
